driver.sources += $(burn.path)/neogeo/d_neogeo.cpp

burn.objects += burn-neogeo-d_neogeo
burn.objects += burn-neogeo-decrypt
burn.objects += burn-neogeo-palette
burn.objects += burn-neogeo-run
burn.objects += burn-neogeo-sprite
burn.objects += burn-neogeo-text
burn.objects += burn-neogeo-upd4990a
burn.objects += burn-neogeo-neogeo

$(object.path)/burn-neogeo-d_neogeo.o: $(burn.path)/neogeo/d_neogeo.cpp
$(object.path)/burn-neogeo-decrypt.o: $(burn.path)/neogeo/neo_decrypt.cpp
$(object.path)/burn-neogeo-palette.o: $(burn.path)/neogeo/neo_palette.cpp
$(object.path)/burn-neogeo-run.o: $(burn.path)/neogeo/neo_run.cpp
$(object.path)/burn-neogeo-sprite.o: $(burn.path)/neogeo/neo_sprite.cpp
$(object.path)/burn-neogeo-text.o: $(burn.path)/neogeo/neo_text.cpp
$(object.path)/burn-neogeo-upd4990a.o: $(burn.path)/neogeo/neo_upd4990a.cpp
$(object.path)/burn-neogeo-neogeo.o: $(burn.path)/neogeo/neogeo.cpp
