burner.objects := burner-conc
burner.objects += burner-cong
burner.objects += burner-dat
burner.objects += burner-gamc
burner.objects += burner-gami
burner.objects += burner-image
burner.objects += burner-inputbuf
burner.objects += burner-ioapi
burner.objects += burner-luaengine
burner.objects += burner-luasav
burner.objects += burner-misc
burner.objects += burner-nvram
burner.objects += burner-sshot
burner.objects += burner-state
burner.objects += burner-statec
burner.objects += burner-un7z
burner.objects += burner-unzip
burner.objects += burner-zipfn

burner.objects := $(burner.objects:%=$(object.path)/%.o)

$(object.path)/burner-conc.o: $(burner.path)/conc.cpp
$(object.path)/burner-cong.o: $(burner.path)/cong.cpp
$(object.path)/burner-dat.o: $(burner.path)/dat.cpp
$(object.path)/burner-gamc.o: $(burner.path)/gamc.cpp
$(object.path)/burner-gami.o: $(burner.path)/gami.cpp
$(object.path)/burner-image.o: $(burner.path)/image.cpp
$(object.path)/burner-inputbuf.o: $(burner.path)/inputbuf.cpp
$(object.path)/burner-ioapi.o: $(burner.path)/ioapi.c
$(object.path)/burner-luaengine.o: $(burner.path)/luaengine.cpp
$(object.path)/burner-luasav.o: $(burner.path)/luasav.cpp
$(object.path)/burner-misc.o: $(burner.path)/misc.cpp
$(object.path)/burner-nvram.o: $(burner.path)/nvram.cpp
$(object.path)/burner-sshot.o: $(burner.path)/sshot.cpp
$(object.path)/burner-state.o: $(burner.path)/state.cpp
$(object.path)/burner-statec.o: $(burner.path)/statec.cpp
$(object.path)/burner-un7z.o: $(burner.path)/un7z.cpp
$(object.path)/burner-unzip.o: $(burner.path)/unzip.c
$(object.path)/burner-zipfn.o: $(burner.path)/zipfn.cpp
