// This file was generated by ../scripts/gamelist.pl (perl 5.036001)

// Declaration of all drivers
#define DRV extern struct BurnDriver
DRV		BurnDrvyard1085;
DRV		BurnDrvyardj10;
DRV		BurnDrvyard10;
DRV		BurnDrvAirass;
DRV		BurnDrvAirdueljm72;
DRV		BurnDrvAirduelu;
DRV		BurnDrvAirduelm72;
DRV		BurnDrvAirduel;
DRV		BurnDrvAlpha1v;
DRV		BurnDrvAtomboya;
DRV		BurnDrvAtomboy;
DRV		BurnDrvAtompunk;
DRV		BurnDrvBchopper;
DRV		BurnDrvBmaster;
DRV		BurnDrvBombrman;
DRV		BurnDrvBbmanwj;
DRV		BurnDrvBbmanwja;
DRV		BurnDrvBbmanw;
DRV		BurnDrvBuccanrs;
DRV		BurnDrvBuccanrsa;
DRV		BurnDrvBuccanrsb;
DRV		BurnDrvCosmccop;
DRV		BurnDrvCrossbld;
DRV		BurnDrvDkgensanm72;
DRV		BurnDrvDkgensanm82;
DRV		BurnDrvDkgensan;
DRV		BurnDrvDicegame;
DRV		BurnDrvDbreedjm72;
DRV		BurnDrvDbreedm72;
DRV		BurnDrvDbreed;
DRV		BurnDrvDsoccr94j;
DRV		BurnDrvDsoccr94k;
DRV		BurnDrvDsoccr94;
DRV		BurnDrvDynablst;
DRV		BurnDrvFghtbskt;
DRV		BurnDrvFirebarr;
DRV		BurnDrvGallopm72;
DRV		BurnDrvGallop;
DRV		BurnDrvGeostorm;
DRV		BurnDrvGunforc2;
DRV		BurnDrvGunforcej;
DRV		BurnDrvGunforceu;
DRV		BurnDrvGunforce;
DRV		BurnDrvGussun;
DRV		BurnDrvHharryu;
DRV		BurnDrvHharry;
DRV		BurnDrvHharryb;
DRV		BurnDrvHasamu;
DRV		BurnDrvHook1v4;
DRV		BurnDrvHook6h;
DRV		BurnDrvHookjy;
DRV		BurnDrvHookbo;
DRV		BurnDrvHooknx2;
DRV		BurnDrvHooknx;
DRV		BurnDrvHookj;
DRV		BurnDrvHookhd2;
DRV		BurnDrvHookhd;
DRV		BurnDrvHookpls;
DRV		BurnDrvHookpj;
DRV		BurnDrvHookdszz;
DRV		BurnDrvHooksw;
DRV		BurnDrvHookgs2;
DRV		BurnDrvHookgs;
DRV		BurnDrvHooku;
DRV		BurnDrvHookdw;
DRV		BurnDrvHook;
DRV		BurnDrvHookx2;
DRV		BurnDrvHookxr;
DRV		BurnDrvHookxx;
DRV		BurnDrvHorizon;
DRV		BurnDrvImgfightj;
DRV		BurnDrvImgfightjb;
DRV		BurnDrvImgfight;
DRV		BurnDrvInthuntu;
DRV		BurnDrvInthunt;
DRV		BurnDrvYanchamr;
DRV		BurnDrvKaiteids;
DRV		BurnDrvKengoj;
DRV		BurnDrvKengo;
#if defined FBNEO_DEBUG
DRV		BurnDrvKftgoal;			// no comment [NOT WORKING]
#endif
DRV		BurnDrvKikcubicb;
DRV		BurnDrvKidnikiu;
DRV		BurnDrvKidniki;
DRV		BurnDrvKungfub;
DRV		BurnDrvKungfub2;
DRV		BurnDrvKungfub3;
DRV		BurnDrvKungfumd;
DRV		BurnDrvKungfum;
DRV		BurnDrvKungfub3s;
DRV		BurnDrvLoht_ms;
DRV		BurnDrvLohtj;
DRV		BurnDrvLohtb2;
DRV		BurnDrvLohtb;
DRV		BurnDrvLoht;
DRV		BurnDrvLohtb3;
DRV		BurnDrvLethalth;
DRV		BurnDrvLtswords;
DRV		BurnDrvLithero;
DRV		BurnDrvLdrun;
DRV		BurnDrvLdruna;
DRV		BurnDrvLdrun2;
DRV		BurnDrvLdrun3j;
DRV		BurnDrvLdrun3;
DRV		BurnDrvLdrun4;
DRV		BurnDrvLotlot;
DRV		BurnDrvGunhohki;
DRV		BurnDrvMajtitlej;
DRV		BurnDrvMajtitle;
DRV		BurnDrvMajtitl2j;
DRV		BurnDrvMajtitl2;
DRV		BurnDrvMajtitl2a;
DRV		BurnDrvMajtitl2b;
DRV		BurnDrvMatchit2;
DRV		BurnDrvKikcubic;
DRV		BurnDrvMpatrolw;
DRV		BurnDrvMpatrol;
DRV		BurnDrvMranger;
DRV		BurnDrvMrheli;
DRV		BurnDrvMysticrib;
DRV		BurnDrvMysticri;
DRV		BurnDrvNewapunk;
DRV		BurnDrvNewtangl;
DRV		BurnDrvNbbatmanu;
DRV		BurnDrvNbbatman;
DRV		BurnDrvNbbat1v2;
DRV		BurnDrvNbbat1v4;
DRV		BurnDrvNbbat1v8;
DRV		BurnDrvNbbatmano;
DRV		BurnDrvNbbatmbh;
DRV		BurnDrvNbbatmx2;
DRV		BurnDrvNspirit;
DRV		BurnDrvPsoldier;
DRV		BurnDrvPpan;
DRV		BurnDrvPoundforj;
DRV		BurnDrvPoundforu;
DRV		BurnDrvPoundfor;
DRV		BurnDrvQuizf1;
DRV		BurnDrvRtypejp;
DRV		BurnDrvRtypej;
DRV		BurnDrvRtypem82b;
DRV		BurnDrvRtypeu;
DRV		BurnDrvRtypeb;
DRV		BurnDrvRtype;
DRV		BurnDrvRtype2j;
DRV		BurnDrvRtype2m82b;
DRV		BurnDrvRtype2jc;
DRV		BurnDrvRtype2;
DRV		BurnDrvRtypeleoj;
DRV		BurnDrvRtypeleo;
DRV		BurnDrvRiskchal;
DRV		BurnDrvNspiritj;
DRV		BurnDrvShisen2;
DRV		BurnDrvSpartanx;
DRV		BurnDrvSpelunkrj;
DRV		BurnDrvSpelunk2;
DRV		BurnDrvSpelunkr;
DRV		BurnDrvSsoldier;
DRV		BurnDrvBattroad;
DRV		BurnDrvSkingame;
DRV		BurnDrvSkingame2;
DRV		BurnDrvThndblst;
DRV		BurnDrvTroangel;
DRV		BurnDrvUccopsj;
DRV		BurnDrvUccopsu;
DRV		BurnDrvUccops;
DRV		BurnDrvUccopsaru;
DRV		BurnDrvUccopsar;
DRV		BurnDrvVigilantbl;
DRV		BurnDrvVigilantd;
DRV		BurnDrvVigilanto;
DRV		BurnDrvVigilantb;
DRV		BurnDrvVigilantg;
DRV		BurnDrvVigilanta;
DRV		BurnDrvVigilantc;
DRV		BurnDrvVigilant;
DRV		BurnDrvVs10yardj;
DRV		BurnDrvVs10yardu;
DRV		BurnDrvVs10yard;
DRV		BurnDrvWilytowr;
#if defined FBNEO_DEBUG
DRV		BurnDrvWpksoc;			// no comment [NOT WORKING]
#endif
DRV		BurnDrvXmultiplm72;
DRV		BurnDrvXmultipl;
DRV		BurnDrvLeaguemn;
DRV		BurnDrvleaguemna;
DRV		BurnDrvYoujyudn;
#undef DRV

// Structure containing addresses of all drivers
// Needs to be kept sorted (using the full game name as the key) to prevent problems with the gamelist in Kaillera
static struct BurnDriver* pDriver[] = {
	&BurnDrvyard1085,			// 10-Yard Fight '85 (US, Taito license)
	&BurnDrvyardj10,			// 10-Yard Fight (Japan)
	&BurnDrvyard10,				// 10-Yard Fight (World, set 1)
	&BurnDrvAirass,				// Air Assault (World)
	&BurnDrvAirdueljm72,		// Air Duel (Japan, M72 hardware)
	&BurnDrvAirduelu,			// Air Duel (US location test, M82 hardware)
	&BurnDrvAirduelm72,			// Air Duel (World, M72 hardware)
	&BurnDrvAirduel,			// Air Duel (World, M82 hardware)
	&BurnDrvAlpha1v,			// Alpha One (Vision Electronics)
	&BurnDrvAtomboya,			// Atomic Boy (revision A)
	&BurnDrvAtomboy,			// Atomic Boy (revision B)
	&BurnDrvAtompunk,			// Atomic Punk (US)
	&BurnDrvBchopper,			// Battle Chopper (World)
	&BurnDrvBmaster,			// Blade Master (World)
	&BurnDrvBombrman,			// Bomber Man (Japan)
	&BurnDrvBbmanwj,			// Bomber Man World (Japan)
	&BurnDrvBbmanwja,			// Bomber Man World (Japan, revised sound hardware)
	&BurnDrvBbmanw,				// Bomber Man World / New Dyna Blaster - Global Quest
	&BurnDrvBuccanrs,			// Buccaneers (set 1)
	&BurnDrvBuccanrsa,			// Buccaneers (set 2)
	&BurnDrvBuccanrsb,			// Buccaneers (set 3, harder)
	&BurnDrvCosmccop,			// Cosmic Cop (World)
	&BurnDrvCrossbld,			// Cross Blades! (Japan)
	&BurnDrvDkgensanm72,		// Daiku no Gensan (Japan, M72 hardware)
	&BurnDrvDkgensanm82,		// Daiku no Gensan (Japan, M82 hardware)
	&BurnDrvDkgensan,			// Daiku no Gensan (Japan, M84 hardware)
	&BurnDrvDicegame,			// Dice - The Dice Game!
	&BurnDrvDbreedjm72,			// Dragon Breed (Japan, M72 hardware)
	&BurnDrvDbreedm72,			// Dragon Breed (World, M72 hardware)
	&BurnDrvDbreed,				// Dragon Breed (World, M81 hardware)
	&BurnDrvDsoccr94j,			// Dream Soccer '94 (Japan, M92 hardware)
	&BurnDrvDsoccr94k,			// Dream Soccer '94 (Korea, M107 hardware)
	&BurnDrvDsoccr94,			// Dream Soccer '94 (World, M107 hardware)
	&BurnDrvDynablst,			// Dynablaster / Bomber Man
	&BurnDrvFghtbskt,			// Fighting Basketball
	&BurnDrvFirebarr,			// Fire Barrel (Japan)
	&BurnDrvGallopm72,			// Gallop - Armed Police Unit (Japan, M72 hardware)
	&BurnDrvGallop,				// Gallop - Armed Police Unit (Japan, M84 hardware)
	&BurnDrvGeostorm,			// Geo Storm (Japan, 014 custom sound CPU)
	&BurnDrvGunforc2,			// Gun Force II (US)
	&BurnDrvGunforcej,			// Gunforce - Battle Fire Engulfed Terror Island (Japan)
	&BurnDrvGunforceu,			// Gunforce - Battle Fire Engulfed Terror Island (US)
	&BurnDrvGunforce,			// Gunforce - Battle Fire Engulfed Terror Island (World)
	&BurnDrvGussun,				// Gussun Oyoyo (Japan)
	&BurnDrvHharryu,			// Hammerin' Harry (US, M84 hardware)
	&BurnDrvHharry,				// Hammerin' Harry (World, M81 hardware)
	&BurnDrvHharryb,			// Hammerin' Harry (World, M84 hardware bootleg)
	&BurnDrvHasamu,				// Hasamu (Japan)
	&BurnDrvHook1v4,			// Hook (1v4, Hack)
	&BurnDrvHook6h,				// Hook (6th Emperor, Hack)
	&BurnDrvHookjy,				// Hook (Elite, Hack)
	&BurnDrvHookbo,				// Hook (Gai Gai, Hack)
	&BurnDrvHooknx2,			// Hook (Hook's Reversal II, Hack)
	&BurnDrvHooknx,				// Hook (Hook's Reversal, Hack)
	&BurnDrvHookj,				// Hook (Japan)
	&BurnDrvHookhd2,			// Hook (Pirate Wars II, Hack)
	&BurnDrvHookhd,				// Hook (Pirate Wars, Hack)
	&BurnDrvHookpls,			// Hook (Plus, Hack)
	&BurnDrvHookpj,				// Hook (POK KAI, Hack)
	&BurnDrvHookdszz,			// Hook (Summit War, Hack)
	&BurnDrvHooksw,				// Hook (SW, Hack)
	&BurnDrvHookgs2,			// Hook (The Expendables II, Hack)
	&BurnDrvHookgs,				// Hook (The Expendables, Hack)
	&BurnDrvHooku,				// Hook (US)
	&BurnDrvHookdw,				// Hook (Warriors, Hack)
	&BurnDrvHook,				// Hook (World)
	&BurnDrvHookx2,				// Hook (X2, Hack)
	&BurnDrvHookxr,				// Hook (Xin Er, Hack)
	&BurnDrvHookxx,				// Hook (XX, Hack)
	&BurnDrvHorizon,			// Horizon (Irem)
	&BurnDrvImgfightj,			// Image Fight (Japan)
	&BurnDrvImgfightjb,			// Image Fight (Japan, bootleg)
	&BurnDrvImgfight,			// Image Fight (World)
	&BurnDrvInthuntu,			// In The Hunt (US)
	&BurnDrvInthunt,			// In The Hunt (World)
	&BurnDrvYanchamr,			// Kaiketsu Yanchamaru (Japan)
	&BurnDrvKaiteids,			// Kaitei Daisensou (Japan)
	&BurnDrvKengoj,				// Ken-Go (Japan)
	&BurnDrvKengo,				// Ken-Go (World)
#if defined FBNEO_DEBUG
	&BurnDrvKftgoal,			// Kick for the Goal [no comment, NOT WORKING]
#endif
	&BurnDrvKikcubicb,			// Kickle Cubele
	&BurnDrvKidnikiu,			// Kid Niki - Radical Ninja (US)
	&BurnDrvKidniki,			// Kid Niki - Radical Ninja (World)
	&BurnDrvKungfub,			// Kung-Fu Master (bootleg set 1)
	&BurnDrvKungfub2,			// Kung-Fu Master (bootleg set 2)
	&BurnDrvKungfub3,			// Kung-Fu Master (bootleg set 3)
	&BurnDrvKungfumd,			// Kung-Fu Master (US)
	&BurnDrvKungfum,			// Kung-Fu Master (World)
	&BurnDrvKungfub3s,			// Kung-Fu Senjyo (bootleg, Spanish)
	&BurnDrvLoht_ms,			// Legend of Hero Tonma (Gaelco bootleg, Modular System) [no comment, NOT WORKING]
	&BurnDrvLohtj,				// Legend of Hero Tonma (Japan)
	&BurnDrvLohtb2,				// Legend of Hero Tonma (Japan, bootleg with i8751)
	&BurnDrvLohtb,				// Legend of Hero Tonma (Playmark unprotected bootleg)
	&BurnDrvLoht,				// Legend of Hero Tonma (World)
	&BurnDrvLohtb3,				// Legend of Hero Tonma (World, bootleg with i8751)
	&BurnDrvLethalth,			// Lethal Thunder (World)
	&BurnDrvLtswords,			// Lightning Swords (World)
	&BurnDrvLithero,			// Little Hero
	&BurnDrvLdrun,				// Lode Runner (set 1)
	&BurnDrvLdruna,				// Lode Runner (set 2)
	&BurnDrvLdrun2,				// Lode Runner II - The Bungeling Strikes Back
	&BurnDrvLdrun3j,			// Lode Runner III - Majin no Fukkatsu (Japan)
	&BurnDrvLdrun3,				// Lode Runner III - The Golden Labyrinth
	&BurnDrvLdrun4,				// Lode Runner IV - Teikoku Karano Dasshutsu (Japan)
	&BurnDrvLotlot,				// Lot Lot
	&BurnDrvGunhohki,			// Mahou Keibitai Gun Hohki (Japan)
	&BurnDrvMajtitlej,			// Major Title (Japan)
	&BurnDrvMajtitle,			// Major Title (World)
	&BurnDrvMajtitl2j,			// Major Title 2 (Japan)
	&BurnDrvMajtitl2,			// Major Title 2 (World, set 1)
	&BurnDrvMajtitl2a,			// Major Title 2 (World, set 1, alt sound CPU)
	&BurnDrvMajtitl2b,			// Major Title 2 (World, set 2)
	&BurnDrvMatchit2,			// Match It II
	&BurnDrvKikcubic,			// Meikyu Jima (Japan)
	&BurnDrvMpatrolw,			// Moon Patrol (Williams)
	&BurnDrvMpatrol,			// Moon Patrol
	&BurnDrvMranger,			// Moon Ranger (bootleg of Moon Patrol)
	&BurnDrvMrheli,				// Mr. HELI no Daibouken (Japan)
	&BurnDrvMysticrib,			// Mystic Riders (bootleg?)
	&BurnDrvMysticri,			// Mystic Riders (World)
	&BurnDrvNewapunk,			// New Atomic Punk - Global Quest (US)
	&BurnDrvNewtangl,			// New Tropical Angel
	&BurnDrvNbbatmanu,			// Ninja Baseball Bat Man (US)
	&BurnDrvNbbatman,			// Ninja Baseball Bat Man (World)
	&BurnDrvNbbat1v2,			// Ninja Baseball Batman (1v2, Hack)
	&BurnDrvNbbat1v4,			// Ninja Baseball Batman (1v4, Hack)
	&BurnDrvNbbat1v8,			// Ninja Baseball Batman (1v8, Hack)
	&BurnDrvNbbatmano,			// Ninja Baseball Batman (One Key Edition, Hack)
	&BurnDrvNbbatmbh,			// Ninja Baseball Batman (Transform, Hack)
	&BurnDrvNbbatmx2,			// Ninja Baseball Batman (X2, Hack)
	&BurnDrvNspirit,			// Ninja Spirit (World)
	&BurnDrvPsoldier,			// Perfect Soldiers (Japan)
	&BurnDrvPpan,				// Peter Pan (bootleg of Hook)
	&BurnDrvPoundforj,			// Pound for Pound (Japan)
	&BurnDrvPoundforu,			// Pound for Pound (US)
	&BurnDrvPoundfor,			// Pound for Pound (World)
	&BurnDrvQuizf1,				// Quiz F1 1-2 Finish (Japan)
	&BurnDrvRtypejp,			// R-Type (Japan prototype)
	&BurnDrvRtypej,				// R-Type (Japan)
	&BurnDrvRtypem82b,			// R-Type (Japan, bootleg M82 conversion)
	&BurnDrvRtypeu,				// R-Type (US)
	&BurnDrvRtypeb,				// R-Type (World bootleg)
	&BurnDrvRtype,				// R-Type (World)
	&BurnDrvRtype2j,			// R-Type II (Japan)
	&BurnDrvRtype2m82b,			// R-Type II (Japan, bootleg M82 conversion)
	&BurnDrvRtype2jc,			// R-Type II (Japan, revision C)
	&BurnDrvRtype2,				// R-Type II (World)
	&BurnDrvRtypeleoj,			// R-Type Leo (Japan)
	&BurnDrvRtypeleo,			// R-Type Leo (World)
	&BurnDrvRiskchal,			// Risky Challenge
	&BurnDrvNspiritj,			// Saigo no Nindou (Japan)
	&BurnDrvShisen2,			// Shisensho II
	&BurnDrvSpartanx,			// Spartan X (Japan)
	&BurnDrvSpelunkrj,			// Spelunker (Japan)
	&BurnDrvSpelunk2,			// Spelunker II - 23 no Kagi (Japan)
	&BurnDrvSpelunkr,			// Spelunker
	&BurnDrvSsoldier,			// Superior Soldiers (US)
	&BurnDrvBattroad,			// The Battle-Road
	&BurnDrvSkingame,			// The Irem Skins Game (US set 1)
	&BurnDrvSkingame2,			// The Irem Skins Game (US set 2)
	&BurnDrvThndblst,			// Thunder Blaster (Japan)
	&BurnDrvTroangel,			// Tropical Angel
	&BurnDrvUccopsj,			// Undercover Cops (Japan)
	&BurnDrvUccopsu,			// Undercover Cops (US)
	&BurnDrvUccops,				// Undercover Cops (World)
	&BurnDrvUccopsaru,			// Undercover Cops - Alpha Renewal Version (US)
	&BurnDrvUccopsar,			// Undercover Cops - Alpha Renewal Version (World)
	&BurnDrvVigilantbl,			// Vigilante (bootleg)
	&BurnDrvVigilantd,			// Vigilante (Japan, Rev D)
	&BurnDrvVigilanto,			// Vigilante (US)
	&BurnDrvVigilantb,			// Vigilante (US, Rev B)
	&BurnDrvVigilantg,			// Vigilante (US, Rev G)
	&BurnDrvVigilanta,			// Vigilante (World, Rev A)
	&BurnDrvVigilantc,			// Vigilante (World, Rev C)
	&BurnDrvVigilant,			// Vigilante (World, Rev E)
	&BurnDrvVs10yardj,			// Vs 10-Yard Fight (Japan)
	&BurnDrvVs10yardu,			// Vs 10-Yard Fight (US, Taito license)
	&BurnDrvVs10yard,			// Vs 10-Yard Fight (World, 11/05/84)
	&BurnDrvWilytowr,			// Wily Tower
#if defined FBNEO_DEBUG
	&BurnDrvWpksoc,				// World PK Soccer [no comment, NOT WORKING]
#endif
	&BurnDrvXmultiplm72,		// X Multiply (Japan, M72 hardware)
	&BurnDrvXmultipl,			// X Multiply (World, M81 hardware)
	&BurnDrvLeaguemn,			// Yakyuu Kakutou League-Man (Japan, set 1)
	&BurnDrvleaguemna,			// Yakyuu Kakutou League-Man (Japan, set 2)
	&BurnDrvYoujyudn,			// Youjyuden (Japan)
};

// Lookup table containing sourcefiles of all drivers
struct game_sourcefile_entry {
	char game_name[32];
	char sourcefile[32];
};

static game_sourcefile_entry sourcefile_table[] = {
	{ "10yard85", "irem/d_m58.cpp"},
	{ "10yardj", "irem/d_m58.cpp"},
	{ "10yard", "irem/d_m58.cpp"},
	{ "airass", "irem/d_m107.cpp"},
	{ "airdueljm72", "irem/d_m72.cpp"},
	{ "airduelu", "irem/d_m72.cpp"},
	{ "airduelm72", "irem/d_m72.cpp"},
	{ "airduel", "irem/d_m72.cpp"},
	{ "alpha1v", "irem/d_m52.cpp"},
	{ "atomboya", "irem/d_m63.cpp"},
	{ "atomboy", "irem/d_m63.cpp"},
	{ "atompunk", "irem/d_m90.cpp"},
	{ "bchopper", "irem/d_m72.cpp"},
	{ "bmaster", "irem/d_m92.cpp"},
	{ "bombrman", "irem/d_m90.cpp"},
	{ "bbmanwj", "irem/d_m90.cpp"},
	{ "bbmanwja", "irem/d_m90.cpp"},
	{ "bbmanw", "irem/d_m90.cpp"},
	{ "buccanrs", "irem/d_vigilant.cpp"},
	{ "buccanrsa", "irem/d_vigilant.cpp"},
	{ "buccanrsb", "irem/d_vigilant.cpp"},
	{ "cosmccop", "irem/d_m72.cpp"},
	{ "crossbld", "irem/d_m92.cpp"},
	{ "dkgensanm72", "irem/d_m72.cpp"},
	{ "dkgensanm82", "irem/d_m72.cpp"},
	{ "dkgensan", "irem/d_m72.cpp"},
	{ "dicegame", "irem/d_m90.cpp"},
	{ "dbreedjm72", "irem/d_m72.cpp"},
	{ "dbreedm72", "irem/d_m72.cpp"},
	{ "dbreed", "irem/d_m72.cpp"},
	{ "dsoccr94j", "irem/d_m92.cpp"},
	{ "dsoccr94k", "irem/d_m107.cpp"},
	{ "dsoccr94", "irem/d_m107.cpp"},
	{ "dynablst", "irem/d_m90.cpp"},
	{ "fghtbskt", "irem/d_m63.cpp"},
	{ "firebarr", "irem/d_m107.cpp"},
	{ "gallopm72", "irem/d_m72.cpp"},
	{ "gallop", "irem/d_m72.cpp"},
	{ "geostorm", "irem/d_m92.cpp"},
	{ "gunforc2", "irem/d_m92.cpp"},
	{ "gunforcej", "irem/d_m92.cpp"},
	{ "gunforceu", "irem/d_m92.cpp"},
	{ "gunforce", "irem/d_m92.cpp"},
	{ "gussun", "irem/d_m90.cpp"},
	{ "hharryu", "irem/d_m72.cpp"},
	{ "hharry", "irem/d_m72.cpp"},
	{ "hharryb", "irem/d_m72.cpp"},
	{ "hasamu", "irem/d_m90.cpp"},
	{ "hook1v4", "irem/d_m92.cpp"},
	{ "hook6h", "irem/d_m92.cpp"},
	{ "hookjy", "irem/d_m92.cpp"},
	{ "hookbo", "irem/d_m92.cpp"},
	{ "hooknx2", "irem/d_m92.cpp"},
	{ "hooknx", "irem/d_m92.cpp"},
	{ "hookj", "irem/d_m92.cpp"},
	{ "hookhd2", "irem/d_m92.cpp"},
	{ "hookhd", "irem/d_m92.cpp"},
	{ "hookpls", "irem/d_m92.cpp"},
	{ "hookpj", "irem/d_m92.cpp"},
	{ "hookdszz", "irem/d_m92.cpp"},
	{ "hooksw", "irem/d_m92.cpp"},
	{ "hookgs2", "irem/d_m92.cpp"},
	{ "hookgs", "irem/d_m92.cpp"},
	{ "hooku", "irem/d_m92.cpp"},
	{ "hookdw", "irem/d_m92.cpp"},
	{ "hook", "irem/d_m92.cpp"},
	{ "hookx2", "irem/d_m92.cpp"},
	{ "hookxr", "irem/d_m92.cpp"},
	{ "hookxx", "irem/d_m92.cpp"},
	{ "horizon", "irem/d_m62.cpp"},
	{ "imgfightj", "irem/d_m72.cpp"},
	{ "imgfightjb", "irem/d_m72.cpp"},
	{ "imgfight", "irem/d_m72.cpp"},
	{ "inthuntu", "irem/d_m92.cpp"},
	{ "inthunt", "irem/d_m92.cpp"},
	{ "yanchamr", "irem/d_m62.cpp"},
	{ "kaiteids", "irem/d_m92.cpp"},
	{ "kengoj", "irem/d_m72.cpp"},
	{ "kengo", "irem/d_m72.cpp"},
	{ "kftgoal", "irem/d_m107.cpp"},
	{ "kikcubicb", "irem/d_vigilant.cpp"},
	{ "kidnikiu", "irem/d_m62.cpp"},
	{ "kidniki", "irem/d_m62.cpp"},
	{ "kungfub", "irem/d_m62.cpp"},
	{ "kungfub2", "irem/d_m62.cpp"},
	{ "kungfub3", "irem/d_m62.cpp"},
	{ "kungfumd", "irem/d_m62.cpp"},
	{ "kungfum", "irem/d_m62.cpp"},
	{ "kungfub3s", "irem/d_m62.cpp"},
	{ "loht_ms", "irem/d_m72.cpp"},
	{ "lohtj", "irem/d_m72.cpp"},
	{ "lohtb2", "irem/d_m72.cpp"},
	{ "lohtb", "irem/d_m72.cpp"},
	{ "loht", "irem/d_m72.cpp"},
	{ "lohtb3", "irem/d_m72.cpp"},
	{ "lethalth", "irem/d_m92.cpp"},
	{ "ltswords", "irem/d_m72.cpp"},
	{ "lithero", "irem/d_m62.cpp"},
	{ "ldrun", "irem/d_m62.cpp"},
	{ "ldruna", "irem/d_m62.cpp"},
	{ "ldrun2", "irem/d_m62.cpp"},
	{ "ldrun3j", "irem/d_m62.cpp"},
	{ "ldrun3", "irem/d_m62.cpp"},
	{ "ldrun4", "irem/d_m62.cpp"},
	{ "lotlot", "irem/d_m62.cpp"},
	{ "gunhohki", "irem/d_m92.cpp"},
	{ "majtitlej", "irem/d_m72.cpp"},
	{ "majtitle", "irem/d_m72.cpp"},
	{ "majtitl2j", "irem/d_m92.cpp"},
	{ "majtitl2", "irem/d_m92.cpp"},
	{ "majtitl2a", "irem/d_m92.cpp"},
	{ "majtitl2b", "irem/d_m92.cpp"},
	{ "matchit2", "irem/d_m90.cpp"},
	{ "kikcubic", "irem/d_vigilant.cpp"},
	{ "mpatrolw", "irem/d_m52.cpp"},
	{ "mpatrol", "irem/d_m52.cpp"},
	{ "mranger", "irem/d_m52.cpp"},
	{ "mrheli", "irem/d_m72.cpp"},
	{ "mysticrib", "irem/d_m92.cpp"},
	{ "mysticri", "irem/d_m92.cpp"},
	{ "newapunk", "irem/d_m90.cpp"},
	{ "newtangl", "irem/d_m57.cpp"},
	{ "nbbatmanu", "irem/d_m92.cpp"},
	{ "nbbatman", "irem/d_m92.cpp"},
	{ "nbbat1v2", "irem/d_m92.cpp"},
	{ "nbbat1v4", "irem/d_m92.cpp"},
	{ "nbbat1v8", "irem/d_m92.cpp"},
	{ "nbbatmano", "irem/d_m92.cpp"},
	{ "nbbatmbh", "irem/d_m92.cpp"},
	{ "nbbatmx2", "irem/d_m92.cpp"},
	{ "nspirit", "irem/d_m72.cpp"},
	{ "psoldier", "irem/d_m92.cpp"},
	{ "ppan", "irem/d_m92.cpp"},
	{ "poundforj", "irem/d_m72.cpp"},
	{ "poundforu", "irem/d_m72.cpp"},
	{ "poundfor", "irem/d_m72.cpp"},
	{ "quizf1", "irem/d_m90.cpp"},
	{ "rtypejp", "irem/d_m72.cpp"},
	{ "rtypej", "irem/d_m72.cpp"},
	{ "rtypem82b", "irem/d_m72.cpp"},
	{ "rtypeu", "irem/d_m72.cpp"},
	{ "rtypeb", "irem/d_m72.cpp"},
	{ "rtype", "irem/d_m72.cpp"},
	{ "rtype2j", "irem/d_m72.cpp"},
	{ "rtype2m82b", "irem/d_m72.cpp"},
	{ "rtype2jc", "irem/d_m72.cpp"},
	{ "rtype2", "irem/d_m72.cpp"},
	{ "rtypeleoj", "irem/d_m92.cpp"},
	{ "rtypeleo", "irem/d_m92.cpp"},
	{ "riskchal", "irem/d_m90.cpp"},
	{ "nspiritj", "irem/d_m72.cpp"},
	{ "shisen2", "irem/d_m90.cpp"},
	{ "spartanx", "irem/d_m62.cpp"},
	{ "spelunkrj", "irem/d_m62.cpp"},
	{ "spelunk2", "irem/d_m62.cpp"},
	{ "spelunkr", "irem/d_m62.cpp"},
	{ "ssoldier", "irem/d_m92.cpp"},
	{ "battroad", "irem/d_m62.cpp"},
	{ "skingame", "irem/d_m92.cpp"},
	{ "skingame2", "irem/d_m92.cpp"},
	{ "thndblst", "irem/d_m92.cpp"},
	{ "troangel", "irem/d_m57.cpp"},
	{ "uccopsj", "irem/d_m92.cpp"},
	{ "uccopsu", "irem/d_m92.cpp"},
	{ "uccops", "irem/d_m92.cpp"},
	{ "uccopsaru", "irem/d_m92.cpp"},
	{ "uccopsar", "irem/d_m92.cpp"},
	{ "vigilantbl", "irem/d_vigilant.cpp"},
	{ "vigilantd", "irem/d_vigilant.cpp"},
	{ "vigilanto", "irem/d_vigilant.cpp"},
	{ "vigilantb", "irem/d_vigilant.cpp"},
	{ "vigilantg", "irem/d_vigilant.cpp"},
	{ "vigilanta", "irem/d_vigilant.cpp"},
	{ "vigilantc", "irem/d_vigilant.cpp"},
	{ "vigilant", "irem/d_vigilant.cpp"},
	{ "vs10yardj", "irem/d_m58.cpp"},
	{ "vs10yardu", "irem/d_m58.cpp"},
	{ "vs10yard", "irem/d_m58.cpp"},
	{ "wilytowr", "irem/d_m63.cpp"},
	{ "wpksoc", "irem/d_m107.cpp"},
	{ "xmultiplm72", "irem/d_m72.cpp"},
	{ "xmultipl", "irem/d_m72.cpp"},
	{ "leaguemn", "irem/d_m92.cpp"},
	{ "leaguemna", "irem/d_m92.cpp"},
	{ "youjyudn", "irem/d_m62.cpp"},
	{ "\0", "\0"}
};
